### ISSUE TITLE
Not respecting overridden ComputeThrottleKey method

### ISSUE THREAD

**Issue by jlkoneczny** [stefanprodan/WebApiThrottle#104]
I'm overriding the ComputeThrottleKey method to make a shorter key that follows our standard for keys, but the code seems to only use the core class's method.

**Comment by jlkoneczny** [comment]
Created pull request [105](https://github.com/stefanprodan/WebApiThrottle/pull/105) to fix this issue.

**Comment by stefanprodan** [comment]
Your changes have been published to nuget v1.5.3

Thanks
