### ISSUE TITLE
how to use Endpoint throttling with difference HTTP Method

### ISSUE THREAD

**Issue by iyanitra** [stefanprodan/WebApiThrottle#17]
Hi stefan,

Currently i have same Endpoint name but it has the different HTTP Method,
this is my Endpoint example:
GET http://localhost:11625/api/userdetai?UserID=1
and
DELETE http://localhost:11625/api/userdetai?UserID=1

my question is: how to make this request has different rate limit for each HTTP method?

**Comment by khorvat** [comment]
BTW is OPTIONS method included in rate limits - does it counts ?

**Comment by stefanprodan** [comment]
@khorvat the throttler doesn't care about the HttpVerb, it will rate limit any request.

Sorry for the late answer
