### ISSUE TITLE
Should not prescribe request identity

### ISSUE THREAD

**Issue by danielcrenna** [stefanprodan/WebApiThrottle#22]
There are so many ways to identify requests in systems, the architecture should not enforce its own header for this purpose, but rather provide an interface to let the consuming application decide how a request identity is defined (from a header, or any mechanism of their choosing, such as identifying anonymous users)

**Comment by stefanprodan** [comment]
I am not enforcing the identity mechanism, I'm just providing a default. If you want to implement your own identity method you can by overriding the default one, take a look at the [documentation](https://github.com/stefanprodan/WebApiThrottle#retrieving-api-client-key) or at issue #27
