### ISSUE TITLE
Throttling requests to "token" endpoint using Microsoft.Owin.Security.OAuth

### ISSUE THREAD

**Issue by chrisgundersen** [stefanprodan/WebApiThrottle#24]
I'm using the Microsoft.Owin.Security.OAuth package to provide token generation in my app - is there a  way to configure WebApiThrottle to limit requests to the "token" endpoint? I've tried doing so using endpoint rules in both the C# code and in the web.config but with no success.

**Comment by Korayem** [comment]
we have same issue here. This is a huge risk.

**Comment by stefanprodan** [comment]
The problem is that the OAuth2 middleware intercepts the request to `/Token` before reaching ThrottlingMiddleware. The only solution I'm thinking of is to register throttling middleware before OAuth. As far as I know you can't specify the order of middlewares execution, is currently determined based on the order of registration.

**Comment by Korayem** [comment]
Will try altering middleware order and see if it works. Thanks.

**Comment by matte5031** [comment]
@chrisgundersen @Korayem  did you manage to do this?

**Comment by dmarlow** [comment]
Does anyone have an example of the proper way to register the middleware before the OAuth config? When I do it before, it's still not being throttled properly. I see the other endpoints are though. I'd like to only throttle the token endpoint and not have any other endpoint affected by the throttling logic.

**Comment by dmarlow** [comment]
Scratch that. I got it working, but all endpoints are affected. I tried using MapWhen, but that broke things. Is there a way to only target a specific endpoint?

**Comment by dmarlow** [comment]
Scratch that again. I found the answer to my question. Looks like you can do a branch using app.MapWhen and get things scoped to just the endpoints you want.

**Comment by ashwinimoily** [comment]
Hi, Do you have an example for this? It would help a lot. thanks.
