### ISSUE TITLE
dependency on System.Web.Http 5.0.0.0

### ISSUE THREAD

**Issue by billhainaut** [stefanprodan/WebApiThrottle#25]
The documentation seems to suggest a depency on System.Web.Http 5.0.0.0 or greater. I have System.Web.Http version 5.2.2.0 and I'm blowing this exception:

Could not load file or assembly 'System.Web.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

**Comment by CezarCretu** [comment]
Do you have a [binding redirect](https://msdn.microsoft.com/en-us/library/eftw1fys%28v=vs.110%29.aspx) configured that hints to the runtime to load 5.2.2 instead of 5.0.0?
