### ISSUE TITLE
IP Address extraction should be configurable

### ISSUE THREAD

**Issue by millarma** [stefanprodan/WebApiThrottle#27]
We have a load balancer in front of our web apps and the ipaddress throttle is all based on the load balancer ip. We have Forwarded_For http header which contains the source ip address but there is no easy way I can see to configure the throttle to use this.

**Comment by stefanprodan** [comment]
The default IP extraction method can be changed, please take a look at the [documentation](https://github.com/stefanprodan/WebApiThrottle#retrieving-api-client-key)

``` cs
public class  LoadBalancerThrottlingHandler : ThrottlingHandler
{
    protected override RequestIdentity SetIndentity(HttpRequestMessage request)
    {
        return new RequestIdentity()
        {
            ClientKey = request.Headers.Contains("Authorization-Key") ? request.Headers.GetValues("Authorization-Key").First() : "anon",
            ClientIp = request.Headers.Contains("Forwarded_For") ? request.Headers.GetValues("Forwarded_For").First() : base.GetClientIp(request).ToString(),
            Endpoint = request.RequestUri.AbsolutePath
        };
    }
}
```

**Comment by millarma** [comment]
Many thanks, this works great. Great package.
