### ISSUE TITLE
SetIndentity of ThrottlingHandler misspelled

### ISSUE THREAD

**Issue by scottlerch** [stefanprodan/WebApiThrottle#29]
I realize this would be a breaking change now but SetIndentity of ThrottlingHandler is misspelled.  Should be *Identity* not Indentity.

**Comment by Korayem** [comment]
#54 duplicate

**Comment by meywd** [comment]
Maybe add a method with the correct spelling and deprecate the old one!

**Comment by stefanprodan** [comment]
I'm working on porting this to ASP.NET Core, when I will finish I will resolve this issue and publish WebApiThrottle v2.  v2 will be the last version to support .NET 4.5

**Comment by meywd** [comment]
aha that's great news
