### ISSUE TITLE
Send informational headers on every response

### ISSUE THREAD

**Issue by azzlack** [stefanprodan/WebApiThrottle#30]
Would be nice to send the `X-Rate-Limit-Limit`, `X-Rate-Limit-Remaining`, `X-Rate-Limit-Reset` headers back on each response so users of the api can deal with it on their side before it becomes a problem.
Like https://dev.twitter.com/rest/public/rate-limiting

**Comment by MrTomWhite** [comment]
@azzlack 
That sounds like a great idea. Are you planning on trying a pr for this?

**Comment by stefanprodan** [comment]
Twitter has a single rate limit period(15 minutes), WebApiThrottle lets you specify multiple periods: per second, minute, hour, day and week. Injecting 15 headers  in the response (3 for each period) will add too much weight to the response. I'am opened to suggestion on how can this be accomplish without polluting the response.

**Comment by escobar5** [comment]
Is there a way to query the values to set this headers in my own Filter?

**Comment by stefanprodan** [comment]
This has been implemented in the [ASP.NET Core version](https://github.com/stefanprodan/AspNetCoreRateLimit).

**Comment by graham-saunders** [comment]
I added a custom solution under #126 for the non-core version of this
