### ISSUE TITLE
IPAddress.Parse doesn't support Port numbers

### ISSUE THREAD

**Issue by khalidabuhakmeh** [stefanprodan/WebApiThrottle#34]
We ran into an interesting use case where the port number came through with the IP address. 

``` text
Message: [FormatException: An invalid IP address was specified.]
 System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse):0
 WebApiThrottle.ThrottlingCore.ContainsIp(List`1 ipRules, String clientIp):7
 WebApiThrottle.ThrottlingCore.IsWhitelisted(RequestIdentity requestIdentity):8
 WebApiThrottle.ThrottlingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken):128
 System.Web.Http.HttpServer+<SendAsync>d__0.MoveNext():285
```

The IP address coming through had port numbers on the end of it. For example:

> 127.0.0.1:8080

This doesn't get parsed. You may want to do some cleanup on IpAddress strings before attempting to parse them.

P.S. This happened in an Azure environment.

If you think this is an issue that should be handled in this project I wouldn't mind submitting a PR.

**Comment by stefanprodan** [comment]
A PR would be great
