### ISSUE TITLE
strong name signing

### ISSUE THREAD

**Issue by HaroonSaid** [stefanprodan/WebApiThrottle#39]
can you publish the nuget package with strong name signing? 
We sign all our assemblies prior to release to our customers and we cant build our system without your assembly being signed

**Comment by tharun236** [comment]
Any luck on this with latest version of Web API Throttle Nuget Package ?

**Comment by tsieberg** [comment]
I also encountered this issue and wanted to cast my vote for signing the assembly.

**Comment by stefanprodan** [comment]
The strong-named package is on NuGet:

```
Install-Package WebApiThrottle.StrongName
```
