### ISSUE TITLE
Question: How do I customize the response of the handler when quota exceeded?

### ISSUE THREAD

**Issue by Payetus** [stefanprodan/WebApiThrottle#45]
I am using the Throttle handler and right now it is return a http error 429 with the following body:

<anyType xmlns:q1="http://www.w3.org/2001/XMLSchema" xmlns:p2="http://www.w3.org/2001/XMLSchema-instance" p2:type="q1:string">
API calls quota exceeded! maximum admitted 1 per Minute.
</anyType>

My api needs to return a very specific structure of response it is a requirement is there anyway to do that?

**Comment by stefanprodan** [comment]
Hello,

You can make your own handler by inheriting from ThrottlingHandler and override [QuotaExceededResponse](https://github.com/stefanprodan/WebApiThrottle/blob/master/WebApiThrottle/ThrottlingHandler.cs#L229)
