### ISSUE TITLE
Question: When overriding QuotaExceedResponse, how do I know the reason for the quota Exceed ( Endpoint or IP)?

### ISSUE THREAD

**Issue by Payetus** [stefanprodan/WebApiThrottle#46]
I am inheriting from ThrottlingHandler and override QuotaExceededResponse, so Ican return the response in the format i wish.  
My policy has IpThrotthling, but I have also custom rates for a specific endpoint. 
And in my response I want to add information about if quota has been exceeded because of the endpoint quota or because of IP quota, is there anyway i could do that?

**Comment by stefanprodan** [comment]
Hello,

You can't since the rate type doesn't get logged see https://github.com/stefanprodan/WebApiThrottle/blob/master/WebApiThrottle/ThrottlingHandler.cs#L154

**Comment by Payetus** [comment]
Yes, I read the code and didn't think it was possible. 
I think it's an interesting feature, I need this  feature for my project I will probably fork WebApiThrottle.
Thank you!
