### ISSUE TITLE
Question: Can I whitelist a specific Endpoint?

### ISSUE THREAD

**Issue by Payetus** [stefanprodan/WebApiThrottle#47]

**Comment by stefanprodan** [comment]
Yes you can, there is an EndpointWhitelist in the [ThrottlePolicy](https://github.com/stefanprodan/WebApiThrottle/blob/master/WebApiThrottle/ThrottlePolicy.cs) or if you are using the attribute-based rate limiting there is a DisableThrotting attribute, please take a look at the [readme](https://github.com/stefanprodan/WebApiThrottle#attribute-based-rate-limiting-with-throttlingfilter-and-enablethrottlingattribute) file it's all in there.

**Comment by Payetus** [comment]
I am throtling by *Ip, but i want a specific endpoint to be excluded from the ip throttling is that possible?

**Comment by stefanprodan** [comment]
You need to enable endpoint throttling and fill the white list, take a look at the exclusion code https://github.com/stefanprodan/WebApiThrottle/blob/master/WebApiThrottle/ThrottlingCore.cs#L158

**Comment by bandisudhir** [comment]
I want to allow only one IP to access my services. Is there any possibility?
