### ISSUE TITLE
Throttling status code

### ISSUE THREAD

**Issue by niemyjski** [stefanprodan/WebApiThrottle#51]
Is it possible to specify a status code to return when the limit is reached?

**Comment by mleonelli** [comment]
In ThrottlingHandler.cs, line 59, you can change the HttpStatusCode set by default to 429

**Comment by niemyjski** [comment]
I get that, but I was looking for a generic solution :)

**Comment by mleonelli** [comment]
Generic as in? The property is public and has set/getter in ThrottlingHandler class
