### ISSUE TITLE
Question : More fine grained throttling

### ISSUE THREAD

**Issue by Roonerelli** [stefanprodan/WebApiThrottle#59]
Hi 

I understand you can set your policy like so:

Policy = new ThrottlePolicy(perSecond: 1, perMinute: 20, perHour: 200, perDay: 1500, perWeek: 3000)

Is it possible to set a policy that allows one request every 5 seconds?

If I set perMinute: 12 , that seems to allow 12 in the first few seconds of a minute and then nothing afterwards

What I would like is to only allow one request, then the next allowed one is five seconds later

I assume fractional values for perSecond dont work

thanks

**Comment by stefanprodan** [comment]
You can't do that with current implementation.

**Comment by Roonerelli** [comment]
ah ok, that's a shame,  thanks for the quick response
