### ISSUE TITLE
ThrottlingMiddleware - Retrieving API Client Key

### ISSUE THREAD

**Issue by meywd** [stefanprodan/WebApiThrottle#64]
As stated in the documentation, to get the client API key from a custom header, one needs to override the `ThrottlingHandler.SetIndentity` function

However, if we use the ThrottlingMiddleware, how can this be done?

**Comment by stefanprodan** [comment]
Same way of course, make your own ThrottlingMiddleware and override SetIndentity

**Comment by meywd** [comment]
Oh missed that, thanks for the help
