### ISSUE TITLE
asp.net core package

### ISSUE THREAD

**Issue by sANDwORm** [stefanprodan/WebApiThrottle#65]

**Comment by stefanprodan** [comment]
I'm developing this in a different project, the new rate limiter deals with various limitations that WebApiThrottle has.
KestrelRateLimit is almost done, take a look here: https://github.com/stefanprodan/KestrelRateLimit

**Comment by sANDwORm** [comment]
Oh, that's great. Looking forward it.

**Comment by sANDwORm** [comment]
I am just looking on your project and it looks great.

I am just starting with .net core so please excuse my ignorance but I would
recommend not to use "ILoggerFactory loggerFactory" in constructor with
following loggerFactory.CreateLogger and switch to
"ILogger<ClientRateLimitMiddleware> logger" and let DI to deal with it?

Cheers,
  Roman


2016-07-26 16:22 GMT+02:00 Stefan Prodan <notifications@github.com>:

**Comment by stefanprodan** [comment]
Good point, I was trying to implement a custom logger like in WebApiThrottle but I find it redundant. I forgot to change back to ILogger<T>.

Thanks
