### ISSUE TITLE
Not working properly in work networks (diffrent users with same ip)

### ISSUE THREAD

**Issue by AlirezaMirmahdi** [stefanprodan/WebApiThrottle#68]
this module doesn't work properly in work networks and throttles all requests from different clients with same IP.
I mean this module doesn't care about sessions and looks at all users in workgroups with the same eye.
users don't need to login in my project so I didn't used Identity to have any client Key.
Is there any option to solve this problem ??

thanks 
alireza

**Comment by stefanprodan** [comment]
If can't differentiate clients then there is no way to apply a rate limit on them.
