### ISSUE TITLE
How can I throttle perMonth?

### ISSUE THREAD

**Issue by NanditaReshamwala** [stefanprodan/WebApiThrottle#70]
hi,

Thank you Stefan for your answer just before on other issue, I closed that issue. I have another question, we have to throttle PerMonth, Is it possible?

**Comment by stefanprodan** [comment]
You can't do that directly, as an workaround you can split your month limit in 4 and rate limit per week. This is one of the limitation of WebApiThrottle that I have addressed in the ASP.NET Core port. When you'll migrate your solution to .NET Core you can use [AspNetCoreRateLimit](https://github.com/stefanprodan/AspNetCoreRateLimit) where you can specify custom time ranges for the rate limits.

**Comment by NanditaReshamwala** [comment]
hi Stefan ,

Thank you for your prompt response. Is there anyway I can write handler when limit is reached. My idea is that I update the policy run time (perWeek in my case) when the limit is  about to reach.

**Comment by stefanprodan** [comment]
You can override the rate limit logic here [ThrottlingHandler](https://github.com/stefanprodan/WebApiThrottle/blob/master/WebApiThrottle/ThrottlingHandler.cs#L132) but updating the perWeek limit to solve the perMonth issue does't look good to me.

**Comment by NanditaReshamwala** [comment]
Thank you Stefan for guidelines.

**Comment by NanditaReshamwala** [comment]
hi Stefan,

I tried to override ThrottlingHandler method you suggested previously to override rate limit logic, but I think ThrottlingCore is not accessible outside of  WebApiThrottle library. 

Would you please help me  how can I extend/override rate limit logic to support for perMonth.  We can  not upgrade our project to.NET core at this stage.

Thank you.

**Comment by NanditaReshamwala** [comment]
hi Stefan,

My manager decided  pricing  perWeek, so I can use in built behaviour. 

Thank you.
