### ISSUE TITLE
ThrottlingHandler doesn't save policy to policy repository when using custom repository

### ISSUE THREAD

**Issue by RGKaizen** [stefanprodan/WebApiThrottle#71]
Hi, I'm not 100% if this is a bug, but here's where I'm at. If I do:

```
            configuration.MessageHandlers.Add(new CustomThrottlingHandler
            {
                Policy = ThrottlePolicy.FromStore(new PolicyConfigurationProvider()),
                PolicyRepository = _NinjectManager.Kernel.Get<IPolicyRepository>()
            });
```

The policy is not saved in the PolicyRepository.

```
    public ThrottlingHandler(ThrottlePolicy policy, IPolicyRepository policyRepository, IThrottleRepository repository, IThrottleLogger logger, IIpAddressParser ipAddressParser = null)
    {
      ...
      this.policy = policy;
      this.policyRepository = policyRepository;
      if (policyRepository == null)
        return;
      policyRepository.Save(ThrottleManager.GetPolicyKey(), policy);
    }
```
I suspect that this constructor is not actually called in my case and so the policy is not stored in the repository. Later when the throttling core checks the repository for the policy, it doesn't find anything. 

You can test this during runtime by calling:
```
            var policy = _PolicyRepository.FirstOrDefault(ThrottleManager.GetPolicyKey());
```
In my case, this is always null.

If the policy repository is not set in the constructor, the issue disappears. But so long as a custom repository is used, the policy doesn't seem to save in the repository.

Am I missing something?

**Comment by stefanprodan** [comment]
After you create you custom handler you need to call the save method before you add it to the message handlers. Here is an [example](https://github.com/stefanprodan/WebApiThrottle/issues/16#issuecomment-54465966).

**Comment by RGKaizen** [comment]
Excellent! Thank you Stefan.
