### ISSUE TITLE
Load Balancer / Proxy ?

### ISSUE THREAD

**Issue by cristianocoelho** [stefanprodan/WebApiThrottle#72]
Just wondering, does this work with a load balancer/proxy in front of the actual web server? This means, does this handle X-Forwarded-For headers to correctly find out the actual source IP address?

**Comment by stefanprodan** [comment]
Yes, you can implement a custom IP parser like this [one](https://github.com/stefanprodan/WebApiThrottle/blob/master/WebApiThrottle.WebApiDemo/Net/CustomIpAddressParser.cs) and specify the header name that contains the actual client IP. It's also a mention of this use case in the [docs](https://github.com/stefanprodan/WebApiThrottle#custom-ip-address-parsing).
