### ISSUE TITLE
Different devices same wifi/network treated as same

### ISSUE THREAD

**Issue by matte5031** [stefanprodan/WebApiThrottle#73]
I tried calling an endpoint with two diferent mobile devices that share the same wifi connection, they were treated as if they were the same, so when the max was 2 requests per minute only 1 request could be done with each device, is there any solution to this? I got a little bit worried since some places like airports and work places etc  might have alot of users sharing wifi/network and would easily hit the request rates in that case. Any help or input is highly appreciated, thanks!

**Comment by stefanprodan** [comment]
In case you didn't notice the default throttling is done by IP.  You need to disable IpThrottling and enable ClientThrottling. You also need to implement an [API key retrieval](https://github.com/stefanprodan/WebApiThrottle#retrieving-api-client-key) for your clients.

**Comment by matte5031** [comment]
You are right thank you. the same scenario works with client throttling enabled(both devices can do two requests each now as intended). However I've got both  IpThrottling = true  And ClientThrottling = true, and not Ipthrottling = false. Is this working as intended or should I have to have Ipthrottling = false?

**Comment by stefanprodan** [comment]
That depends on what you want. 

If you have a 2 req/sec limit and both ClientThrottling and Ipthrottling are enabled, a client using 2 devices will be rate limited at 4 req/sec if he uses both devices in the same time. If you disable the Ipthrottling then no matter how many devices your client is using, he will be rate limited at 2 req/sec.

**Comment by matte5031** [comment]
Yeah okay, that is if the client has different keys correct @stefanprodan ? Now all different devices has different authorization keys so it was 4 req/sec with Ipthrottling disabled(same if it was enabled, it didn't really matter if it was enabled or disabled). I had to override the ThrottlingHandler.SetIdentity. Can I override it and use it within the web.config instead somehow? I need to use throttle from the config file, else the /Token endpoint won't be throttled. Thanks!

**Comment by stefanprodan** [comment]
Overriding the ThrottlingHandler.SetIdentity doesn't affect reading the rules from config.
