### ISSUE TITLE
expect an example about oauth

### ISSUE THREAD

**Issue by seven1986** [stefanprodan/WebApiThrottle#76]
Thanks a  lot
When client got accessToken they do need appkey with any request, So how can I limit the request before valiate accessToken?
I am going to use it in my product envirment, so could you help me? thanks

**Comment by stefanprodan** [comment]
First you'll need to protect OAuth `/Token` endpoint using the `ThrottlingMiddleware` with `IpThrottling` enabled. You need to register the `ThrottlingMiddleware` before the OAuth middleware, see this [issue](https://github.com/stefanprodan/WebApiThrottle/issues/24) for more details.

When a user is authorize, you'll have to add a claim to the identity store, like userId or whatever you use to uniquely identify your clients.  Then you can override the `ThrottlingHandler.SetIdentity` function and use that claim as the throttle key. Something like this:

```cs
public class OAuthThrottlingHandler : ThrottlingHandler
{
    protected override RequestIdentity SetIdentity(HttpRequestMessage request)
    {
          var userId = "anon";
         if(request.GetRequestContext().Principal.Identity.IsAuthenticated)
         {
            //get userId from identity claim 
         }
        return new RequestIdentity()
        {
            ClientKey = userId,
            ClientIp = base.GetClientIp(request).ToString(),
            Endpoint = request.RequestUri.AbsolutePath.ToLowerInvariant()
        };
    }
```

**Comment by seven1276** [comment]
Thanks,It works,fantastic!
And must put this code ` app.Use<OAuthThrottlingMiddleware>();` after `app.use OAuth API` 

One more question I want to know is about 
![image](https://cloud.githubusercontent.com/assets/3192191/20244691/a01c8740-a9c6-11e6-9ed9-3aabb49b86a3.png)


SetIdentity does not excute when I write 'base.PolicyRepository = new PolicyMemoryCacheRepository()'

**Comment by stefanprodan** [comment]
Build your Policy outside the OAuthThrottlingMiddleware:

```cs
public class Startup
{
    public void Configuration(IAppBuilder appBuilder)
    {
        var oauthPolicy = BuildPolicyFromDB();

        appBuilder.Use(typeof(OAuthThrottlingMiddleware),
            oauthPolicy,
            new PolicyMemoryCacheRepository(),
            new MemoryCacheRepository(),
            null,
            null);
    }
}
```
