### ISSUE TITLE
Couldnot load file or assembly 

### ISSUE THREAD

**Issue by tharun236** [stefanprodan/WebApiThrottle#77]
Hi Stefan,
I am trying to add WebAPI Throttle Nuget to avoid any DOS attacks to Web API. I have downloaded the Nuget and added below lines in webapiconfig.cs. 

config.MessageHandlers.Add(new ThrottlingHandler()
            {
                Policy = new ThrottlePolicy(perSecond: 1, perMinute: 30)
                {
                    IpThrottling=true
                },
                Repository = new CacheRepository()
            });

WebApiThrotle NuGet Version - 1.5.1
Visual Studio Version - 2015, .NET 4.5.2, Azure version -2.9
I was able to build but while running the web api seeing below error while trying to register in Global.asax.cs

**Error**:  An exception of type 'System.IO.FileLoadException' occurred in System.Web.Http.WebHost.dll but was not handled in user code
Could not load file or assembly 'WebApiThrottle, Version=1.5.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

Please let me know if the NuGet package is created without stong-name or else any other issue.

**Comment by stefanprodan** [comment]
The strong-named package is on NuGet:

```
Install-Package WebApiThrottle.StrongName
```

PS. I'm getting some reports that starting with WebApiThrottle v1.5.1 the client IP parsing is broken on Azure ARR. Please submit an issue if you encounter any problems running in Azure. Thanks.

**Comment by tharun236** [comment]
Sure Stefan. Will keep an eye and will respond if come across it.
