### ISSUE TITLE
set PesponsePolicy = true

### ISSUE THREAD

**Issue by seven1276** [stefanprodan/WebApiThrottle#79]
For example, when I set PesponsePolicy = true
then It will response some infomattion to header like this:
X-Rate-Limit-Quota：当前 AppKey 一个时间窗口内可调用次数
X-Rate-Limit-Remaining：当前时间窗口剩余的可用次数
X-Rate-Limit-Reset：距离时间窗口重置剩余的秒数

**Comment by stefanprodan** [comment]
There is no PesponsePolicy

**Comment by seven1276** [comment]
I just think it could be usefull, some times... I wanna response remaining,quato,reset with every call, so that caller will know clearly

**Comment by stefanprodan** [comment]
This has been implemented [here](https://github.com/stefanprodan/WebApiThrottle/pull/36) but it didn't make it into the master. The current implementation would make X-Rate very noise since there are multiple limits you can set and adding 3 headers per limit will pollute the response.
