### ISSUE TITLE
using URL Segment in Endpoint custom rate limit does not seem to work

### ISSUE THREAD

**Issue by mmsundaram** [stefanprodan/WebApiThrottle#86]
Hi @stefanprodan .! 

Thanks a lot for putting up such an awesome library online. 

I was trying to use REDIS cache to store the policy and the metrics and was able to do that just by following the inputs on the readme. Wonderfully written.! :) I can add those repository files and the handler config here if you think that might be useful. 

Then I had a scenario that I will have Path Params in my request. I was trying to implement Endpoint custom rate limit based on URL segment Just like in readme but couldn't get it to work.  Am I missing something.? 

Here is my configuration : 
`throttlePolicy = new ThrottlePolicy(perDay: 5)
{
ClientThrottling = true,
                    EndpointThrottling = true,
                    ClientWhitelist = new List<string>(){ "ADMIN-API-KEY" },
                    EndpointRules = new Dictionary<string, RateLimits> {
                        {"/agents/", new RateLimits {PerDay = 0}},
                        {"/properties/", new RateLimits {PerDay = 1}},
                        {"/data/", new RateLimits {PerDay = 1}},
                        {"/routing/", new RateLimits {PerDay = 1}},
                        {"/singapore/", new RateLimits {PerDay = 1}},
                        {"/places/", new RateLimits {PerDay = 1}},
                        {"/units/", new RateLimits {PerDay = 1}}
                        }
                };`

Thanks.!
Meenakshi Sundaram

**Comment by stefanprodan** [comment]
Can you try with `/agents` or with the full prefix like `api/agents`?

**Comment by mmsundaram** [comment]
Here is a sample API request for Agents : 
`http://<<My-Api-Domain>>/agents/123`

I don't have a prefix, its a standalone WebAPI where agents is a resource(controller) and I have other operations on the agents as well like `http://<<My-Api-Domain>>/agents/123/availability`

I have tried these things for now : 
`/agents`
`/agents/`

The throttling works as such. I mean, the limits are applied for the entire URL -> http://<<My-Api-Domain>>/agents/123 (cant access it more than once a day) 
but I can still request another agent using /agents/125. This way, the user might be able to get each of the agent once a day.

**Comment by stefanprodan** [comment]
Yes, this is the intended behavior see docs [here](https://github.com/stefanprodan/WebApiThrottle#endpoint-throttling-based-on-ip)

**Comment by mmsundaram** [comment]
ah.! i got carried away with the URL segment in the endpoint routing. Thanks for pointing it out. :) Is there a way I would be able to achieve what i want by implementing any interface.? or is it part of the core system.?

**Comment by stefanprodan** [comment]
You could override [SetIdentity](https://github.com/stefanprodan/WebApiThrottle#retrieving-api-client-key) and remove all URL parts except the first and set the `endpoint` to that single part.

**Comment by mmsundaram** [comment]
That's awesome.! thanks 👍
